### ISSUE TITLE
Default database

### ISSUE THREAD

**Issue by osauzet** [greenstatic/bigbluebutton-exporter#1]
When i add the grafana dashboard I have no data...
My target are OK on prometheus because i see it on prometheus dashboard...
But when i edit one graph on grafana, i see the defaut database , but not prometheus... :
You can see here : https://pasteboard.co/J0K8t7y.png

could you understand why i dont have a source 'prometheus'... 

My grafana have some other databases (influxdb)

Thanks for your work :-)

**Comment by greenstatic** [comment]
Have you added Prometheus as a data source in Grafana? On the screenshot you sent I can clearly see the query is not for Prometheus but for Influx (default).

**Comment by osauzet** [comment]
I have this settings for variables in the dashboard : https://pasteboard.co/J0KjmoS.png

**Comment by greenstatic** [comment]
This is just the query for the variable `instance` which is used to filter the metrics in the per instance dashboard, not for the panel queries. I see you have correctly setup your Prometheus in Grafana since we can see the instances of bigbluebutton-exporter you have configured in Prometheus (under "Preview of values" in your screenshot). 

I suspect the problem is that my default data source is Prometheus while yours is Influx however in the dashboard the queries are defined against the default. Which is why it works for me. I will update the dashboard to have the data source set as Prometheus explicitly which should fix the problem. I'll try to push the updated dashboard within the hour. 

In the mean time you can for the participants panel change the query from default to Prometheus and report back if that fixes your problem (this will only fix the participants panel and not the rest). This will confirm my suspicions regarding the issue.

**Comment by osauzet** [comment]
I changed the base for the "participants" but I'm not sure that it is in the right place, or the recipe for the number of participants does not fit correctly : https://pasteboard.co/J0KrxZg.png
Thanks for your help !

**Comment by greenstatic** [comment]
It seems that when you changed the query source it erased the query.
I replaced the data source of the BBB All Servers dashboard to be explicitly set to Prometheus. Can you give it a try and report back?


[grafana_dashboard_all_servers__data_source_prometheus_fix.zip](https://github.com/greenstatic/bigbluebutton-exporter/files/4381974/grafana_dashboard_all_servers__data_source_prometheus_fix.zip)

**Comment by osauzet** [comment]
Yeah ! its seams OK, 
But one question, why i see two entry ? not juste  one (i have one server bbb)
https://pasteboard.co/J0KKVsF.png
Thanks

**Comment by greenstatic** [comment]
I assume you changed in the Prometheus config (prometheus.yml) your targets in your job definition? Run the following query in Prometheus: `bbb_api_up` and check the `instance` value. There should be both values which you see in the dashboard. I recommend you check online how to delete values from the old instance you configured. Or simply edit the `instance` variable in Grafana by filtering out the unwanted value or by hard coding your desired instance value.

I will shortly update the BBB Server Instance Grafana dashboard to also have Prometheus as the query data source. You might be interested in importing that one as well, especially if you only have one server since it gives you much more valuable details (CPU vs. participants, etc.). For the BBB Server Instance dashboard [Netdata](https://docs.netdata.cloud/) is required. It's very simple to install so it shouldn't be a big burden. Do not forget to configure Prometheus to scrape Netadata, instructions to do so: https://docs.netdata.cloud/backends/prometheus/

**Comment by osauzet** [comment]
ok, thanks for all the advice, i will correct my data sources on prometheus and wait for your other dashboards. Actually I have to install Netdata ... (and upgrade prometheus 1.x to 2.x, but its another story)
Thank you very much for your help and your response time :-)
