### ISSUE TITLE
All-In-One Monitoring Stack: sudo docker-compose up -d fails

### ISSUE THREAD

**Issue by Maupard** [greenstatic/bigbluebutton-exporter#21]
I installed BBB (on Ubuntu 16.04) but without Greenlight, thus I didn't have docker.
I installed it via 
`apt-get install docker docker-compose`
But when I run 
`sudo docker-compose up -d`
I get 
```
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

My Docker-Version is:
```
root@bbb:~/bbb-monitoring# docker --version
Docker version 18.09.7, build 2d0083d
```

I'm not familiar with docker

**Comment by greenstatic** [comment]
Can you report your docker-compose version
```shell
docker-compose --version
```

**Comment by Maupard** [comment]
```
docker-compose --version
docker-compose version 1.8.0, build unknown
```

**Comment by greenstatic** [comment]
I assume you used Ubuntu's repository to install docker (you did not follow https://docs.docker.com/engine/install/ubuntu/). The version of Docker you have is nearly a year old (for Docker this is quite old). 

We are running Docker version 19.03.8 in production on our Ubuntu 16.04 LTS BBB servers.

Not that it makes a difference for the compose file, since the compose file version is 3.2 which should support docker engines from 17.04.0+ (https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix).

The main issue is that in Ubuntu's repositories they have a very old version of docker-compose. Your version, 1.8.0 doesn't support compose's version 3.x which is currently recommended by docker.

My recommendation is to uninstall docker and docker-compose from your BBB host, follow Docker's installation instructions to get the latest stable release which should enable you to download a more recent version of docker-compose (we are running `docker-compose version 1.25.4` in production).

**Comment by greenstatic** [comment]
I'll add a note to the documentation to warn other users about the outdated docker & docker-compose releases in Ubuntu's repo. Thanks for the heads up.

**Comment by Maupard** [comment]
That worked
