### ISSUE TITLE
Grafana Dashboards with CPU and RAM usage 

### ISSUE THREAD

**Issue by pcslayer2801** [greenstatic/bigbluebutton-exporter#27]
Hi,

first of all I have to tell you that I think your project is very good. I used your project in my company (we are an IT company that supports schools in our country with the technical infrastructure).  My colleagues think the dashboards are great. And especially when people think something is good, they naturally have suggestions for improvement.
One of them is: Is it possible that the dashboards also show CPU and RAM usage?
I myself am not familiar with Prometheus and Grafana at all; I always copy your configurations. If there is an update, they are simply imported.

Thanks for sharing your project with us :)

**Comment by greenstatic** [comment]
Thanks for the kind words. It really does payoff the effort that goes into creating an open source project that is ready and easy to start using.

I'm not entirely certain I fully understand in which dashboard you wish to display CPU and RAM usage?
1. All servers dashboard
2. Server instance dashboard

In server instance dashboard there already is CPU usage (combined with bandwidth and participants). We could add a simple dashboard for RAM usage but since RAM (at least in my experience) is not usually of concern in BBB this might be better suited in a full blown node_exporter/netdata Grafana dashboard.

For node_exporter I use this dashboard: https://grafana.com/grafana/dashboards/1860

For Netdata I took the following dashboard https://grafana.com/grafana/dashboards/7107 and built upon it to support multiple instances and correctly display network utilization.

**Comment by pcslayer2801** [comment]
thanks for your quick response.
I meant the dashboard with all servers, a small graph with the CPU usage would be enough :)

**Comment by greenstatic** [comment]
We can add that but it will require us to split the dashboard into two (one for node_exporter and the other for netdata) - unless we join both queries into a single panel. Will have to test it out.
