### ISSUE TITLE
Display disk space

### ISSUE THREAD

**Issue by chezmohamed** [greenstatic/bigbluebutton-exporter#63]
is there a possibility to display total disk space and used space ?

**Comment by greenstatic** [comment]
The metrics for storage utilization needs to come from either node_exporter or netdata (depends which one you are using). Generally it is better to have node_exporter's or netdata's specific dashboard which include storage utilization and a whole load of other panels with metrics. You can mostly find these dashboard in the Grafana Dashboard catalog (https://grafana.com/grafana/dashboards) - although from experience sometimes some panel queries need to be fixed.

I could however add storage utilization to the server instance dashboard since it is quite an important metric when dealing with many recordings. I'll look into it in the coming days.

**Comment by chezmohamed** [comment]
Thanks

**Comment by greenstatic** [comment]
I have updated the Grafana dashboard with your request. Just redownload the dashboard from the master branch and import them into your Grafana (make sure to delete the old ones first). Feel free to close the issue.

Implemented in: https://github.com/greenstatic/bigbluebutton-exporter/commit/f8c589f6350d4c3b06dafce120f61f674d634b6a

**Comment by chezmohamed** [comment]
ah great thank you very much

**Comment by chezmohamed** [comment]
Hello
I think there is a small problem on the graph after the update
CPU utilization and Bandwidth do not appear in the graph in the graph
CPU Utilization vs. Participants
Bandwidth vs. Participants

**Comment by greenstatic** [comment]
Have you changed the variables at the top of the dashboard? Specifically the `Job node_exporter` and `Network Interface` variables.

**Comment by chezmohamed** [comment]
Yes 
![image](https://user-images.githubusercontent.com/26858857/96444442-8a0ecd00-120e-11eb-84b5-08f0f7fea60a.png)

**Comment by greenstatic** [comment]
Is it just this dashboard, or the rest as well?

**Comment by greenstatic** [comment]
Try changing the `Datasource` and `Instance` variables.

**Comment by chezmohamed** [comment]
I changed but still it doesn't work
it works with another dashboard

**Comment by greenstatic** [comment]
You were right, there was a mistake in the query variables for the node_exporter server instance dashboard. Should be fixed in: https://github.com/greenstatic/bigbluebutton-exporter/commit/300fb5169f48d3864addfa78133a193f66ad0920

Re-download the dashboard and give it a try.

**Comment by chezmohamed** [comment]
Yes now it works wonderfully
![image](https://user-images.githubusercontent.com/26858857/96456943-7c157800-121f-11eb-8207-85ca7641b1f2.png)

Thanks

**Comment by greenstatic** [comment]
Just a tip, if you change the time-range in the top right corner, click save dashboard, there is a checkbox to `Save current time range as dashboard default` and `Save current variable values as dashboard default`. Might be useful to you.

**Comment by chezmohamed** [comment]
Thank you for your advice it is done ;)
