### ISSUE TITLE
Feature request: Get de number of participant by meetting, get the list of meetings names 

### ISSUE THREAD

**Issue by IJOL** [greenstatic/bigbluebutton-exporter#69]
Hi, All:

Great little piece of software, very nice and easy to install at least the all-in-one type of install...

As said we need to add the count of participants by meeting and the list of meetings, by name, I'm pretty sure the first item should be easy, adding labels to the metrics, I don't know already how exactly do it myself, but seems easy maybe..

But how about getting the list of the active meetings as a list in grafana? from my brief ( very brief ) look at the Prometheus python API, I don't found how to do it,

**Comment by greenstatic** [comment]
Getting a list of meetings by name, along with with their count is a no go with Prometheus. Prometheus is for metrics not for logging. Adding the meeting name into the metric is bad practice because it introduces high cardinality - read more about it here: https://prometheus.io/docs/practices/naming/#labels.

Getting meetings by name in Grafana will need to be done without using bigbluebutton-exporter. What you are proposing for is a basic feature and pretty important which is why I have on my todo list some sort of logging integration with BigBlueButton and to display such information in Grafana. Sadly this cannot be implemented by a Prometheus exporter.

As a temporary solution to the same problem I had, I hacked together a simple website that displays a list of meetings and their participants count: https://github.com/greenstatic/bigbluebutton-monitoring
But yeah, a better solution is required with Grafana integration I agree.

**Comment by IJOL** [comment]
Hi Gregor:

Read the link and seen many examples of Grafana dashboards
from kuberntes where labels are used extensively, y have a graphic with
theoretically 120 lines from all my pods in one namespace, seen that I
think that in an installation like mine where hardly we have 6 or seven
simultaneous meetings, to add labels to participants counts and room
metric, some data present in meeting/metadata or alike, didn't seem to me
like a big sin. I will try myself and I will report back maybe a pull
request..,


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by hex-m** [comment]
> Getting a list of meetings by name, along with with their count is a no go with Prometheus. Prometheus is for metrics not for logging.

We just had a similar case. Management would like to know how many meetings we had per day. We don't know when a meeting started/ended, but only know how many were running at some point in time. Therefor we can't know the number of meetings that took place. Can you confirm that my understanding is correct?

**Comment by greenstatic** [comment]
> > Getting a list of meetings by name, along with with their count is a no go with Prometheus. Prometheus is for metrics not for logging.
> 
> We just had a similar case. Management would like to know how many meetings we had per day. We don't know when a meeting started/ended, but only know how many were running at some point in time. Therefor we can't know the number of meetings that took place. Can you confirm that my understanding is correct?

Correct, currently I do not see a way we could calculate that value. But I agree that it is a good metric to have. I will add a new metric, `bbb_meetings_count` which would be a counter that counts unique bbb meetings. Expect a beta during the weekend.

**Comment by greenstatic** [comment]
I have added two counters:
* `bbb_unique_meetings_total`
* `bbb_unique_breakout_rooms_total` 

These are available in the 0.7.0 branch: https://github.com/greenstatic/bigbluebutton-exporter/tree/v0.7.0

I have created a preview docker image as well, tag: [v0.7.0-preview](https://hub.docker.com/layers/greenstatic/bigbluebutton-exporter/v0.7.0-preview/images/sha256-952b13436aa26d49d6787b112bb8be0418d951e617de8f2f0f44c0285557b04c?context=explore)

The node_exporter Grafana dashboard has also been updated (see commits in branch 0.7.0). Although I am not 100% I implemented the queries correctly.

This is all in preview and it might change in the future. Will need to keep an eye on this for the remainder of the week, to see if the panels on Grafana use the coutners correctly.

In the meantime you are welcome to use the preview and provide feedback and/or PRs :)
