### ISSUE TITLE
Unnecessarily promotes third-party netdata

### ISSUE THREAD

**Issue by Natureshadow** [greenstatic/bigbluebutton-exporter#7]
When isntalling the exporter in order to get the dashboard for Grafana, I wondered whether installing that netdata thing is really necessary. It is a really fat applicatio, adds another (untrusted) package source to the system (or another potentially insecure docker container), and by default, it even has usage tracking and phone-home features enabled, which might violate data protection desires or even laws if going unnoticed.

I verified that the dashboard works perfectly when using the standard Prometheus node exporter, which comes bundled with Ubuntu (and Debian and presumably anyhting else). Installign the netdata software is thus unnecessary and, in my opinion, should be dropped from the documentation and replaced with installing the node exporter instead.

**Comment by greenstatic** [comment]
Thank you @Natureshadow for your insight. I agree that netdata is quite heavy and that recommending node_exporter would be better since it is the official plugin from Prometheus. 

But the reason we choose Netdata at the time was because we were facing some issues with BBB (in particular kurento-media-server). Netdata's selling point is that it offers [higher metrics resolution](https://docs.netdata.cloud/docs/why-netdata/1s-granularity/) which gave us more data to work with when debugging our issue. We made sure we disabled telemetry during our own installation, which if I remember correctly is prompted as part of the installation. We decided to leave Netdata in the repository because it is a rather popular and big project (see their GitHub repository) and deemed it good enough.

Since everything (metrics) is working as expected this is quite a low priority for us and it will take us some time to expand the documentation on node_exporter. I am however open to PR that add support for it.
