### ISSUE TITLE
DAU, WAU, MAU

### ISSUE THREAD

**Issue by Nyco** [greenstatic/bigbluebutton-exporter#83]
Hi all,

Thanks for the bbb-ex tool! :)

Some of our users and customers would like to see DAU, WAU, MAU:

- DAU: Daily Active Users
- WAU: Weekly Active Users
- MAU: Monthly Active Users

Not sure it can be easily done, but something approaching may help.

Thanks a lot!

**Comment by greenstatic** [comment]
This sounds more like something that should be implemented by parsing logs and then feeding this data into Grafana, not via infrastructure monitoring. The main issue I have with this is to track an active user it is necessary to store a user's unique identifier (i.e. unique ID, email, etc.). This information should not be stored in Prometheus and saving this in memory in the exporter is a bad idea since upon a restart this data would be gone.

Although I agree this information would be great to have it is out of the scope for this project. The need to add similar (out of scope) functionality to this project has arisen before already and I agree it is functionality that is missing/needed. I might start a separate project that aims to solve this, but currently I cannot promise or give an ETA.

**Comment by Nyco** [comment]
Great answer, thanks a lot! :)
