### ISSUE TITLE
bigbluebutton 2.3.0 monitoring does not work at all

### ISSUE THREAD

**Issue by himpierre** [greenstatic/bigbluebutton-exporter#94]
Hello Devs.

First of all thanks for your work. 

Here is my first experience. Just installed as described in the documentation. All systems running. No errors. Dived through the FAQ but to no avail. My Dashboard stays empty. Have a look at the screenshot.

Do you have a hint for me where to go from here? Cheers, t.

![image](https://user-images.githubusercontent.com/40269193/117172606-3dff3080-adcc-11eb-8791-e16e546cb771.png)

**Comment by himpierre** [comment]
Here a screenshot from prometheus.

![image](https://user-images.githubusercontent.com/40269193/117178418-49edf100-add2-11eb-8024-66391081b4d2.png)

**Comment by himpierre** [comment]
Uhm. It seems only the dashboard is broken.

![image](https://user-images.githubusercontent.com/40269193/117178956-e1534400-add2-11eb-8cef-e352dc879314.png)

**Comment by himpierre** [comment]
Suddenly it works. Don't know why.

**Comment by greenstatic** [comment]
The issue was that the variables were not set in your dashboard. This happens if the query that resolves the variables (viewed under dashboard settings -> variables) does not return the expected values.

If I'm not mistaken the variables are reloaded on dashboard refresh, so when you reloaded the page, it suddenly started working. 

![Screen Shot 2021-05-07 at 12 20 08 AM](https://user-images.githubusercontent.com/14580434/117372596-11314300-aeca-11eb-9d13-704d2b1dc839.png)
